name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6.0.1
      with:
        version: v1.58.2
        args: --version

    - name: Test
      run: make ci
